# Generated by Django 4.2.6 on 2023-11-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrocliente',
            name='login',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
    ]
