# Generated by Django 4.2.6 on 2023-11-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0002_cadastrocliente_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
