# Generated by Django 4.2.6 on 2023-11-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_alter_cadastrocliente_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='login',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='senha',
        ),
    ]
