# Generated by Django 4.2.6 on 2023-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0005_cadastrocliente_login_cadastrocliente_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastrocliente',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
