# Generated by Django 4.2.6 on 2023-11-07 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0002_alter_itemestoque_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='data_adicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
