# Generated by Django 4.2.6 on 2023-11-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0003_itemestoque_data_adicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='data_adicao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
