# Generated by Django 4.2.6 on 2023-11-08 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0004_itemestoque_data_edicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemestoque',
            name='data_edicao',
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='data_adicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
